Fix ggplot2 deprecation warning in DotPlot()
satijalab/seurat pull request #9409
Opened 2024-10-18 09:11 UTC by Billsfriend

# Problem

The `facets` argument of `facet_grid()` is deprecated as of ggplot2 2.2.0. And aes_string() is deprecated as of ggplot2 3.0.0. The warnings are disturbing and will be errors in the future.

# Fix

1. Use `rows`  argument for `facet_grid()`.
2. Switch `aes_string()` to `aes()` and use tidy evaluation idioms.

2025-09-15 21:00 UTC, anashen requested changes
Thanks @Billsfriend for your PR! Please see the requested changes.

2025-09-15 21:00 UTC, anashen commented on R/visualization.R
> +  plot <- ggplot(data = data.plot, mapping = aes(x = .data$features.plot, y = .data$id)) +
```suggestion
  plot <- ggplot(data = data.plot, mapping = aes(x = .data[["features.plot"]], y = .data[["id"]])) +
```

2025-09-15 21:00 UTC, anashen commented on R/visualization.R
> +    geom_point(mapping = aes(size = .data$pct.exp, color = .data[[color.by]])) +
```suggestion
    geom_point(mapping = aes(size = .data[["pct.exp"]], color = .data[[color.by]])) +
```

2025-09-24 01:03 UTC, Billsfriend commented
Thanks @anashen! I see no reason to delay merging this PR.

2025-09-25 15:00 UTC, merged